added debugging steps in actions file

diff --git a/.github/workflows/image-azure.yml b/.github/workflows/image-azure.yml
--- a/.github/workflows/image-azure.yml
+++ b/.github/workflows/image-azure.yml
@@ -83,8 +83,18 @@ jobs:
 
       - name: Build and Push Image
         run: |
+
+          echo "Checking for Dockerfile in server directory..."
+          ls -R server/ | grep Dockerfile || echo "Dockerfile NOT found in server/ folder"
+
+
           IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:${{ github.sha }}
-          docker build -t $IMAGE_TAG -f ./server/Dockerfile ./server/apps/${{ matrix.service }}
+          
+          docker build \
+            -t $IMAGE_TAG \
+            -f server/Dockerfile \
+            ./server/apps/${{ matrix.service }}
+          
           docker push $IMAGE_TAG
 
       - name: Azure Login
